name: single_thread_channel_hierarchy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - shapely
  - numpy
  - scipy
  - pandas
  - pyarrow
  - duckdb
  - tqdm
  - matplotlib
  - plotly
  - jupyterlab
  - notebook
  - ipykernel
